version: '3.8' 

services:
        frontend:
                container_name: frontend
                build: 
                        context: ./frontend
                        dockerfile: Dockerfile
                        #volumes:
                          #- ./node_modules/:/app/node_modules
                ports:
                        - 3000:3000
                # Get output from frontend 
                stdin_open: true
                environment:
                        - CHOKIDAR_USEPOLLING=true # Live reload frontend when UI/UX files change
                depends_on: 
                        - mysqlserver
                        - backend
                        - nginx
                command: npm start

        backend: 
                container_name: backend
                build: 
                        context: ./demo
                        dockerfile: Dockerfile
                volumes:
                        - ./:/server
                ports:
                        - 8000:8000
                depends_on: 
                        - mysqlserver
                        - nginx
                # restart_on: always 
                command: ./gradlew  
                  
        nginx: 
                container_name: nginx
                image: nginx
                build: 
                        context: ./nginx
                        dockerfile: Dockerfile
                volumes: #NOTE If new nginx dir pops up it's because the nginx/ is repeated after it was ser in context
                        - ./nginx/:/etc/nginx/
                ports: 
                        - 8080:80 
                # Do i need to config proxy url here? 
                environment: 
                        - NGINX_HOST=localhost 
                        - NGINX_PORT=80
                #command: nginx -g daemon off #NOTE: Debug mode is on!

        mysqlserver: #TODO setup script for testing 
                image: mysql
                ports:
                        - 3306:3306
                environment: #NOTE ROOT NEEDS PASSWD
                        - MYSQL_ROOT_PASSWORD=
                        - MYSQL_ALLOW_EMPTY_PASSWORD=true
                        - MYSQL_USER=coffeeshopuser
                        - MYSQL_PASSWORD=coffeeshop
                        - MYSQL_DATABASE=ShopDB
                volumes:
                        - mysql_data:/var/lib/mysql
                        - mysql_config:/etc/mysql/conf.d
    #TODO add persistent storage 
volumes:
        mysql_data:
        mysql_config:
