version: '3.9' 

services:
        frontend:
                container_name: frontend
                build:
                        context: ./frontend/
                        dockerfile: Dockerfile
                volumes:
                        - ./frontend/:/frontend/
                ports:
                        - "3000:3000"
                stdin_open: true
                command: "npm start"

        backend:
                container_name: backend
                build:
                        context: ./backend/
                        dockerfile: Dockerfile 
                volumes:
                        - ./backend/:/backend/
                        - ./backend/app.jar:/backend/app.jar 
                ports:
                        - "8000:8000"


                                  #        depends_on: 
                                 #        depends_onmysqlserver
                                 #        depends_onnginx
                # restart_on: always 
                command: "./mvnw sprint-boot:run" 
                  
        nginx: 
                container_name: nginx
                image: nginx:latest
                build: 
                        context: ./nginx
                        dockerfile: Dockerfile
                volumes:
                        - ./nginx/nginx.conf:/nginx/nginx.conf:ro # Read only
                ports: 
                        - "80:8080" 
                environment: 
                        - NGINX_HOST=localhost 
                        - NGINX_PORT=80
                command: "nginx-debug -g, daemon off;" #NOTE: Debug mode is on!

                
        mysqlserver: #TODO setup script for testing 
                image: mysql
                ports:
                        - "3306:3306"
                environment:
                        - MYSQL_ROOT_PASSWORD=
                        - MYSQL_ALLOW_EMPTY_PASSWORD=true
                        - MYSQL_USER=user
                        - MYSQL_PASSWORD=passwd
                        - MYSQL_DATABASE=ShopDB
                volumes:
                        - mysql_data:/var/lib/mysql
                        - mysql_config:/etc/mysql/conf.d
    #TODO add persistent storage 
volumes:
        mysql_data:
        mysql_config:
